# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36934b10fbdc708e4b26303f86082a6f357354060493a1b2b28b27c173269564f25b6af79d5bb17555802ce19d22c1aa4cd4804606e454ae38331c82c51118a3

test:
  secret_key_base: e364ffc374516b421358a6c22fffff9249eee2a5c7c1a09449a9f139f62882bc1e72521dc5f7fd0545a3ebec16600ea247c32151537cb9b57910067219bae3c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
